### ISSUE TITLE
Demos outdate with current version of licode

### ISSUE THREAD

**Issue by woanversace** [lynckia/licode-demos#1]
Can you guys update this ?

**Comment by vaibhaviitm** [comment]
Any update on this issue? I am facing the same problem. Pulled the latest code of litcode-demo and licode. They don't seem to work well. In /admin/login, what should be the credentials? I gave serviceid and servicekey, but it ways "Wrong Credentials".

**Comment by vaibhaviitm** [comment]
![image](https://cloud.githubusercontent.com/assets/777660/20136791/b91a0ba0-a69c-11e6-87d8-41e5ddfd3a67.png)

I gave following credentials, which i got from setting up licode - 
[licode] SuperService ID 5822ab11aa82e0214f80cd86
[licode] SuperService KEY 27164

**Comment by icyield** [comment]
Hi, I also have the same problems as reported above. Clean ubuntu 14. Tried with node@10 and node 6.9.2, as this is used now in the licode code base but always get "wrong credential". And index page does not seem give anything, hangs.

It is a shame that this project has fallen behind, it was good work.

Gerard.

**Comment by aalonsog** [comment]
Have you included those credentials (SuperServiceID and Key) in the config file of licode-server?

**Comment by icyield** [comment]
Sure, Basic example that comes with licode works. 
This is my config file.

me@Ubuntu14:~/licode/licode-demos$ cat config.js
var config = {};

config.nuve_host = 'http://127.0.0.1';
config.service = {};
config.service.id ='591cb2de13d7fdf3ec3eb6ce';
config.service.key = '27895';

config.demo_host = '127.0.0.1'; // Without "http", just the host.

config.http_port = 80;
config.https = false;
config.https_port = 443;
config.ca_certs = undefined;

//config.plain = true;

module.exports = config;

**Comment by icyield** [comment]
Hi. found the issue comparing basic example. 
In the config file the line 
config.nuve_host = 'http://127.0.0.1';  

Should be, 
config.nuve_host = 'http://127.0.0.1:3000/';

Thanks for the spur to make me look again.

**Comment by aalonsog** [comment]
Great!

**Comment by xujun738** [comment]
how to enable ssl?
